CREATE DATABASE IF NOT EXISTS jobsearch;
USE jobsearch;

DROP TABLE IF EXISTS jobs;

CREATE TABLE jobs
(job_id INT PRIMARY KEY,
 job_type varchar(100),
 job_name varchar(200),
 company_name varchar(100),
 location varchar(100),
 date_posted varchar(100)
);

INSERT INTO jobs VALUES(1,'Full-Stack Developer','Full-Stack\u202f.NET\u202fDeveloper\u202f(Web & Desktop)','Whitecap Canada','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(2,'Full-Stack Developer','Java Full Stack Developer (Angular/React) - Hybrid','Cognizant','Ontario, Canada','5 days ago');
INSERT INTO jobs VALUES(3,'Full-Stack Developer','Senior Full Stack Developer','Royal Bank of Canada','Calgary, AB, Canada','14 days ago');
INSERT INTO jobs VALUES(4,'Full-Stack Developer','Full-Stack Developer','DLL','Burlington, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(5,'Full-Stack Developer','Fullstack Developer','Citi','Mississauga, ON, Canada','');
INSERT INTO jobs VALUES(6,'Full-Stack Developer','Full Stack Developer','Accenture','Montreal, Quebec, Canada','');
INSERT INTO jobs VALUES(7,'Full-Stack Developer','full stack developer','SPRH CONSULTING INC.','Oshawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(8,'Full-Stack Developer','Junior Full-Stack Developer','Q Wealth Partners','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(9,'Full-Stack Developer','Intermediate Full Stack Developer','Hitachi Careers','Toronto, ON, Canada','19 days ago');
INSERT INTO jobs VALUES(10,'Full-Stack Developer','Senior Full Stack Developer (Bilingual - French/English)','Graphem Solutions','Burnaby, BC, Canada','20 hours ago');
INSERT INTO jobs VALUES(11,'Software Engineer','Software Engineer, Banking Technology','Manulife','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(12,'Software Engineer','Senior Software Engineer (Full-Stack)','Mastercard','Vancouver, BC, Canada','9 days ago');
INSERT INTO jobs VALUES(13,'Software Engineer','Software Developer 2','Intuit','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(14,'Software Engineer','Online Software Engineer','Electronic Arts (EA)','Burnaby, BC, Canada','5 days ago');
INSERT INTO jobs VALUES(15,'Software Engineer','Software Engineer (Onsite)','RTX','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(16,'Software Engineer','Sr. Software Engineer (Front End)','McGraw Hill LLC.','Canada','');
INSERT INTO jobs VALUES(17,'Software Engineer','Software Engineer II (DevSecOps Engineer)','Planview Incorporated','Vancouver, BC, Canada','27 days ago');
INSERT INTO jobs VALUES(18,'Software Engineer','Senior Staff Software Engineer','Posting Date:07/ 08/2024','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(19,'Software Engineer','Software Development Engineer','Inkeros','Ontario, Canada','3 days ago');
INSERT INTO jobs VALUES(20,'Software Engineer','Senior Software Engineer','Synopsys','Markham, ON, Canada','19 days ago');
INSERT INTO jobs VALUES(21,'Senior Software Engineer','Senior Software Engineer (Full-Stack)','Mastercard','Vancouver, BC, Canada','9 days ago');
INSERT INTO jobs VALUES(22,'Senior Software Engineer','Senior Software Engineer','MEDA Group','Waterloo, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(23,'Senior Software Engineer','Senior Software Engineer, Data Platform','Coinbase','Victoria, BC, Canada','9 hours ago');
INSERT INTO jobs VALUES(24,'Senior Software Engineer','Sr Software Engineer- Remote','BeyondTrust','British Columbia, Canada','3 days ago');
INSERT INTO jobs VALUES(25,'Senior Software Engineer','Senior Software Engineer','Synopsys','Markham, ON, Canada','19 days ago');
INSERT INTO jobs VALUES(26,'Senior Software Engineer','Sr Software Developer','WARNERMEDIA','Kanata, ON, Canada','20 days ago');
INSERT INTO jobs VALUES(27,'Senior Software Engineer','Senior Staff Software Engineer','Posting Date:07/ 08/2024','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(28,'Senior Software Engineer','Remote Senior Software Engineer (Eastern Canada)','Centric Software','Canada','4 days ago');
INSERT INTO jobs VALUES(29,'Senior Software Engineer','Senior Software Engineer (backend) - Toronto','Borderless AI','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(30,'Senior Software Engineer','Sr Software Engineer - Canada','Alstom','Toronto, ON, Canada','13 days ago');
INSERT INTO jobs VALUES(31,'Front End Developer','Front End Developer','Stebr Canada Inc.','Toronto, ON, Canada','6 days ago');
INSERT INTO jobs VALUES(32,'Front End Developer','Front End Engineer','Kiwee Intelligence Inc.','Canada','5 hours ago');
INSERT INTO jobs VALUES(33,'Front End Developer','Senior Frontend Developer','Royal Bank of Canada','Toronto, ON, Canada','20 days ago');
INSERT INTO jobs VALUES(34,'Front End Developer','Axiom - Front-End Developer','Equinox Engineering Ltd.','Calgary, AB, Canada','3 days ago');
INSERT INTO jobs VALUES(35,'Front End Developer','Web Software Developer - Front End (Senior)','dakis','Montreal, Quebec, Canada','3 days ago');
INSERT INTO jobs VALUES(36,'Front End Developer','UI Frontend Developer - EA SPORTS UFC','Electronic Arts (EA)','Burnaby, BC, Canada','2 days ago');
INSERT INTO jobs VALUES(37,'Front End Developer','Front End Developer','Compass Group Canada','Mississauga, ON, Canada','26 days ago');
INSERT INTO jobs VALUES(38,'Front End Developer','Frontend Developer','PDF Solutions','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES(39,'Front End Developer','Front-End Developer','BLAZESOFT','Vaughan, ON, Canada','');
INSERT INTO jobs VALUES(40,'Front End Developer','Front End and Full Stack Developer (Remote - Ontario, Canada ONLY)','Ample Insight Inc.','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(41,'Web Developer','Web developer','Compuran as well as ITD Canada','Vancouver, BC, Canada','3 days ago');
INSERT INTO jobs VALUES(42,'Web Developer','Web Developer � Co-op/Intern','Nokia','Ontario, Canada','2 days ago');
INSERT INTO jobs VALUES(43,'Web Developer','Web Developer','Design Shopp','Canada','');
INSERT INTO jobs VALUES(44,'Web Developer','Web developer','webever technologies','Winnipeg, MB, Canada','3 days ago');
INSERT INTO jobs VALUES(45,'Web Developer','Web Software Developer - Front End (Senior)','dakis','Montreal, Quebec, Canada','3 days ago');
INSERT INTO jobs VALUES(46,'Web Developer','Java Web Developer','STACK IT Recruitment','Mississauga, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(47,'Web Developer','Software Developer (Back End Web Services)','Thales','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(48,'Web Developer','Web Designer & Developer','Apple Blueprints','Canada','1 month ago');
INSERT INTO jobs VALUES(49,'Web Developer','front-end Web developer','SOFTRON TAX','Mississauga, ON, Canada','5 days ago');
INSERT INTO jobs VALUES(50,'Web Developer','Front End Developer','Stebr Canada Inc.','Toronto, ON, Canada','6 days ago');
INSERT INTO jobs VALUES(51,'Developer','AI Software Developer','Merck KGaA, Darmstadt, Germany','Montreal, Quebec, Canada','4 days ago');
INSERT INTO jobs VALUES(52,'Developer','Software Developer - Senior','US Tech Solutions','Markham, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(53,'Developer','Software Developer 2','Intuit','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(54,'Developer','Software Developer II','WARNERMEDIA','Kanata, ON, Canada','1 month ago');
INSERT INTO jobs VALUES(55,'Developer','Principle Software Developer - Montreal','Keywords Studios','Quebec, Canada','6 days ago');
INSERT INTO jobs VALUES(56,'Developer','Software Developer III, AI/ML, Google Cloud AI','Google','Toronto, ON, Canada','4 days ago');
INSERT INTO jobs VALUES(57,'Developer','Software Developer','L3Harris Technologies','Ottawa, ON, Canada','');
INSERT INTO jobs VALUES(58,'Developer','Senior Full Stack Developer','Luxoft','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(59,'Developer','Senior Software Developer, GFT','Royal Bank of Canada','Vancouver, BC, Canada','4 days ago');
INSERT INTO jobs VALUES(60,'Developer','Software Developer � Mobile','Evercommerce','Oakville, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(61,'Net Developer','Sr. Dot Net Developer','Stellar Software Solutions','Halifax, NS, Canada','2 days ago');
INSERT INTO jobs VALUES(62,'Net Developer','Dotnet Developer','Diamondpick','Mississauga, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(63,'Net Developer','.NET Developers','Canada IT Club','Ontario, Canada','3 days ago');
INSERT INTO jobs VALUES(64,'Net Developer','Senior .NET Developer (Sitecore CMS)','Canadian Cancer Society','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(65,'Net Developer','Senior .NET Developer','Mariner Innovations','Fredericton, NB, Canada','5 days ago');
INSERT INTO jobs VALUES(66,'Net Developer','Senior C#/.Net Developer','Societe Generale','Montreal, Quebec, Canada','9 days ago');
INSERT INTO jobs VALUES(67,'Net Developer','.NET Software Developer','CB Canada','New Westminster, BC, Canada','');
INSERT INTO jobs VALUES(68,'Net Developer','Developer Digital Development (.NET MAUI)','Randstad','Toronto, ON, Canada','23 days ago');
INSERT INTO jobs VALUES(69,'Net Developer','P2 - Full Stack Developer - .Net Core','Randstad Canada','Mississauga, ON, Canada','');
INSERT INTO jobs VALUES(70,'Net Developer','.Net Developer','BlazeSoft','Vaughan, ON, Canada','');
INSERT INTO jobs VALUES(71,'Java Developer','Junior Java Developer','Delbridge Solutions','Ontario, Canada','2 days ago');
INSERT INTO jobs VALUES(72,'Java Developer','Java Developer','Scotiabank','Toronto, ON, Canada','5 days ago');
INSERT INTO jobs VALUES(73,'Java Developer','Senior Java Developer','GFL Environmental Inc.','Vaughan, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(74,'Java Developer','Java Developer (GCP/AWS) - Contract - Toronto','CorGTA Inc.','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(75,'Java Developer','Core Java Developer','Iris Software Inc.','Toronto, ON, Canada','4 days ago');
INSERT INTO jobs VALUES(76,'Java Developer','Senior Java Developer','Citi','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(77,'Java Developer','Java Web Developer','STACK IT Recruitment','Mississauga, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(78,'Java Developer','Java Developer','isgSearch','Vaughan, ON, Canada','6 days ago');
INSERT INTO jobs VALUES(79,'Java Developer','Java Developer','Scotiabank','Toronto, ON, Canada','9 days ago');
INSERT INTO jobs VALUES(80,'Java Developer','GTS - Sr. Java Developers ONLY Living outside of Canada- Work Visa Provided - CANADA','Venuiti','Waterloo, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(81,'Application Developer','AI Application Developer � HYBRID (1684)','Direct IT Recruiting Inc., WBE Canada Certified','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(82,'Application Developer','Application Developer Microsoft Power Platform','Artech L.L.C.','Toronto, ON, Canada','6 days ago');
INSERT INTO jobs VALUES(83,'Application Developer','Application Software Developer Lead - (Java / JSON/ AWS / IBM Websphere/ Payments)','Bank of Montreal','Toronto, ON, Canada','4 days ago');
INSERT INTO jobs VALUES(84,'Application Developer','Software Developer 2','Intuit','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(85,'Application Developer','Application Developer II / Senior Software Engineer','Randstad','Toronto, ON, Canada','26 days ago');
INSERT INTO jobs VALUES(86,'Application Developer','Applications Development Tech Lead','Citi','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(87,'Application Developer','Application Developer','Stantec','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES(88,'Application Developer','Web Application Developer Canada','Backlight',"St. John's, NL, Canada",'');
INSERT INTO jobs VALUES(89,'Application Developer','Web Application Developer','Celayix','Vancouver, BC, Canada','26 days ago');
INSERT INTO jobs VALUES(90,'Application Developer','Software Developer II','WARNERMEDIA','Kanata, ON, Canada','1 month ago');
INSERT INTO jobs VALUES(91,'Web Designer','Web Designer & Developer','Apple Blueprints','Canada','1 month ago');
INSERT INTO jobs VALUES(92,'Web Designer','Freelance Website Designer','Websharx','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(93,'Web Designer','Product/Web Designer','OpusClip','Burnaby, BC, Canada','');
INSERT INTO jobs VALUES(94,'Web Designer','Web designer','Canadawide Jobs Inc','Abbotsford, BC, Canada','');
INSERT INTO jobs VALUES(95,'Web Designer','Web Designer','Newfound Recruiting','Ottawa, ON, Canada','9 days ago');
INSERT INTO jobs VALUES(96,'Web Designer','Web Designer / Front-end Developer','Earth Rangers','Ontario, Canada','');
INSERT INTO jobs VALUES(97,'Web Designer','Web designer','Immigration Canada Pro','Ontario, Canada','');
INSERT INTO jobs VALUES(98,'Web Designer','Graphic & Web Designer','Kepler Canada','Richmond Hill, ON, Canada','27 days ago');
INSERT INTO jobs VALUES(99,'Web Designer','Designer, Web Presence (Events)','Stripe','Toronto, ON, Canada','26 days ago');
INSERT INTO jobs VALUES(100,'Web Designer','Web designer - graphic design','RIGHTMOVE DESIGN INC','Abbotsford, BC, Canada','');
INSERT INTO jobs VALUES(101,'Senior Developer','Senior Developer (ServiceNow and Power Platform)','Hays','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(102,'Senior Developer','Senior Software Developer','D2L','Kitchener, ON, Canada','');
INSERT INTO jobs VALUES(103,'Senior Developer','Senior Software Developer, GFT','Royal Bank of Canada','Vancouver, BC, Canada','4 days ago');
INSERT INTO jobs VALUES(104,'Senior Developer','Senior Frontend Developer','Randstad Digital','Oakville, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(105,'Senior Developer','Senior iOS Developer','WARNERMEDIA','Kanata, ON, Canada','1 month ago');
INSERT INTO jobs VALUES(106,'Senior Developer','Software Developer - Senior','US Tech Solutions','Markham, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(107,'Senior Developer','Senior Developer (Kotlin)','Thoughtworks','Toronto, ON, Canada','24 days ago');
INSERT INTO jobs VALUES(108,'Senior Developer','Senior Software Developer, 6+ years - Canada (Remote)','Info-Tech Research Group','Toronto, ON, Canada','11 days ago');
INSERT INTO jobs VALUES(109,'Senior Developer','Sr. Software Engineer (Front End)','McGraw Hill LLC.','Canada','');
INSERT INTO jobs VALUES(110,'Senior Developer','Senior Developer - Canada Wide - Remote','Newton','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(111,'Principal Software Engineer','Principal Software Engineer Team Lead- Canada','Bellwood Labs','Toronto, ON, Canada','6 days ago');
INSERT INTO jobs VALUES(112,'Principal Software Engineer','Senior Staff / Principal Software Developer','Intuit','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(113,'Principal Software Engineer','Principal Software Engineer','Microsoft','Vancouver, BC, Canada','11 days ago');
INSERT INTO jobs VALUES(114,'Principal Software Engineer','Principal Software Engineering Manager - AI performance','Microsoft','Vancouver, BC, Canada','4 days ago');
INSERT INTO jobs VALUES(115,'Principal Software Engineer','Principal Software Engineer 1 - Game of Thrones: Legends','Zynga','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(116,'Principal Software Engineer','Principal Software Engineer 2 - Game Services, ZGMT','Zynga','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(117,'Principal Software Engineer','Principal Software Engineer 1 � Game of Thrones: Legends','Zynga','Canada','3 days ago');
INSERT INTO jobs VALUES(118,'Principal Software Engineer','Principal Software Engineer Team Lead','Bellwood','Canada','4 days ago');
INSERT INTO jobs VALUES(119,'Principal Software Engineer','Principal Software Engineer - Data Platform','Toast','Canada','');
INSERT INTO jobs VALUES(120,'Principal Software Engineer','Principal Software Engineer, AI/ML Platform','Autodesk','Toronto, ON, Canada','17 days ago');
INSERT INTO jobs VALUES(121,'Back End Developer','Backend Developer (Montreal Canada Only)','MagicPace','Montreal, Quebec, Canada','3 days ago');
INSERT INTO jobs VALUES(122,'Back End Developer','Software Developer (Back End Web Services)','Thales','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(123,'Back End Developer','Back End Developer','Expansion','Vaughan, ON, Canada','24 days ago');
INSERT INTO jobs VALUES(124,'Back End Developer','Back End Developer','Boast','Vancouver, BC, Canada','2 days ago');
INSERT INTO jobs VALUES(125,'Back End Developer','Backend Developer - Canada','SysAid Technologies','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(126,'Back End Developer','Lead Backend Developer','Royal Bank of Canada','Toronto, ON, Canada','12 days ago');
INSERT INTO jobs VALUES(127,'Back End Developer','Back End Developer','Robert Half','Toronto, ON, Canada','12 days ago');
INSERT INTO jobs VALUES(128,'Back End Developer','Azure Backend Developer-Canada','Zortech Solutions','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(129,'Back End Developer','Java Back End Developer - IT (Information Technology) - Montreal, Canada','Societe Generale','Montreal, Quebec, Canada','');
INSERT INTO jobs VALUES(130,'Back End Developer','Backend Software Engineer - Cloud Traffic and Networking (Remote - Canada)','Confluent Career Site','Ontario, Canada','12 days ago');
INSERT INTO jobs VALUES(131,'Senior .NET Developer','Senior .NET Developer','Mariner Innovations','Fredericton, NB, Canada','5 days ago');
INSERT INTO jobs VALUES(132,'Senior .NET Developer','Senior .NET Developer','MDA Space','Sainte-Anne-de-Bellevue, Quebec, Canada','19 days ago');
INSERT INTO jobs VALUES(133,'Senior .NET Developer','Senior .NET Developer (Sitecore CMS)','Canadian Cancer Society','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(134,'Senior .NET Developer','.Net Developer','AdventInfotech','Ottawa, ON, Canada','6 days ago');
INSERT INTO jobs VALUES(135,'Senior .NET Developer','Senior .NET Developer/Analyst','Agricorp','Guelph, ON, Canada','7 days ago');
INSERT INTO jobs VALUES(136,'Senior .NET Developer','Senior .net developer to complete the rebuild of an existing software solution into a cloud agnostic application in the public sector.','S.i. Systems','Ottawa, ON, Canada','17 days ago');
INSERT INTO jobs VALUES(137,'Senior .NET Developer','Senior Fullstack developer - Websites Connectivity','Coveo','New Canada, NS, Canada','');
INSERT INTO jobs VALUES(138,'Senior .NET Developer','Senior Net Developer with Net core Angular 12 AND SQL AZURE','Purple Drive','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(139,'Senior .NET Developer','Canada: Sr API Developer (CANAD004085)','ScanSource','Calgary, AB, Canada','3 days ago');
INSERT INTO jobs VALUES(140,'Senior .NET Developer','Senior Software Developer','D2L','Kitchener, ON, Canada','');
INSERT INTO jobs VALUES(141,'Senior Engineer','Dow Canada Senior Engineer Opportunities','THE DOW CHEMICAL COMPANY','Penhold, AB, Canada','6 days ago');
INSERT INTO jobs VALUES(142,'Senior Engineer','Senior Power Systems Engineer | Renewable Energy','Potenco','Ontario, Canada','4 days ago');
INSERT INTO jobs VALUES(143,'Senior Engineer','Senior Structural Engineer','Madison Taylor Design','Midhurst, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(144,'Senior Engineer','Senior Bridge Engineer','Jacobs','Kitchener, ON, Canada','5 days ago');
INSERT INTO jobs VALUES(145,'Senior Engineer','Senior Machine Learning Engineer','BenchSci','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(146,'Senior Engineer','Senior Systems Engineer','Calian Group Ltd.','Ontario, Canada','');
INSERT INTO jobs VALUES(147,'Senior Engineer','Senior II Electrical Engineer','MineSense Technologies Ltd.','Vancouver, BC, Canada','3 days ago');
INSERT INTO jobs VALUES(148,'Senior Engineer','Senior Project Engineer','ABB','Quebec, Canada','25 days ago');
INSERT INTO jobs VALUES(149,'Senior Engineer','Senior Artificial Intelligence Engineer ( Senior Data Scientist - AI)','Compass Group Canada','Mississauga, ON, Canada','4 days ago');
INSERT INTO jobs VALUES(150,'Senior Engineer','Senior Software Engineer (Full-Stack)','Mastercard','Vancouver, BC, Canada','9 days ago');
INSERT INTO jobs VALUES(151,'Senior Java Developer','Senior Java Developer','Citi','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(152,'Senior Java Developer','Senior Java Developer','GFL Environmental Inc.','Vaughan, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(153,'Senior Java Developer','Senior Java Developer','Citi','Mississauga, ON, Canada','');
INSERT INTO jobs VALUES(154,'Senior Java Developer','Senior Java Spark Bigdata Developer','Citi','Mississauga, ON, Canada','');
INSERT INTO jobs VALUES(155,'Senior Java Developer','Senior Java Developer','Fulcrum Digital Inc.','Victoria, BC, Canada','3 days ago');
INSERT INTO jobs VALUES(156,'Senior Java Developer','Senior Java Spring Boot Developer','BrightOrder Inc.','Mississauga, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(157,'Senior Java Developer','Senior Java Spring Boot Developer','BrightOrder Inc.','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(158,'Senior Java Developer','Senior Java Backend Developer','HCPL Global Inc.','Mississauga, ON, Canada','4 days ago');
INSERT INTO jobs VALUES(159,'Senior Java Developer','Senior Java Fullstack with React ( 70 % Backend + 30 % frontend )in','Syntricate Technologies','Mississauga, ON, Canada','5 days ago');
INSERT INTO jobs VALUES(160,'Senior Java Developer','Senior Java Developer','ICE','Calgary, AB, Canada','7 days ago');
INSERT INTO jobs VALUES(161,'Senior Application Developer','Software Developer - Senior','US Tech Solutions','Markham, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(162,'Senior Application Developer','Senior Software Application Engineer','Quarry Consulting','Canada','4 days ago');
INSERT INTO jobs VALUES(163,'Senior Application Developer','Senior Software Developer (Halifax), GFT','Royal Bank of Canada','Nova Scotia, Canada','11 days ago');
INSERT INTO jobs VALUES(164,'Senior Application Developer','Senior Software Engineer (Full Stack Developer)','Tradable Bits','Vancouver, BC, Canada','16 days ago');
INSERT INTO jobs VALUES(165,'Senior Application Developer','Senior Full Stack Developer','Luxoft','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(166,'Senior Application Developer','Senior Software Engineer','Synopsys','Markham, ON, Canada','19 days ago');
INSERT INTO jobs VALUES(167,'Senior Application Developer','Senior Analyst, Application Development and Maintenance','Air Canada','Dorval, Quebec, Canada','');
INSERT INTO jobs VALUES(168,'Senior Application Developer','Senior Software Developer (C#), GFT','Royal Bank of Canada','Toronto, ON, Canada','23 days ago');
INSERT INTO jobs VALUES(169,'Senior Application Developer','Senior Software Development Engineer','remitly','New Westminster, BC, Canada','');
INSERT INTO jobs VALUES(170,'Senior Application Developer','Senior Software Engineer, Data Platform','Coinbase','Victoria, BC, Canada','9 hours ago');
INSERT INTO jobs VALUES(171,'Staff Software Engineer','Staff Software Developer','WARNERMEDIA','Kanata, ON, Canada','');
INSERT INTO jobs VALUES(172,'Staff Software Engineer','Staff Software Engineer - MTS 2','eBay','Toronto, ON, Canada','5 days ago');
INSERT INTO jobs VALUES(173,'Staff Software Engineer','Senior Staff Software Engineer','Posting Date:07/ 08/2024','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(174,'Staff Software Engineer','Staff Frontend Software Engineer','Warner Music Group','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(175,'Staff Software Engineer','Staff Software Engineer - Fullstack - Websites Team','Toast','Canada','');
INSERT INTO jobs VALUES(176,'Staff Software Engineer','Staff Software Engineer - Incident Management','PagerDuty','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(177,'Staff Software Engineer','Staff Software Engineer, Infotainment Platform','Rivian','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES(178,'Staff Software Engineer','Senior Staff / Principal Software Developer','Intuit','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(179,'Staff Software Engineer','Staff Software Engineer','Affinity.co','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(180,'Staff Software Engineer','Staff Software Engineer, Platform Engineering','Lime','Canada','8 days ago');
INSERT INTO jobs VALUES(181,'Cloud Engineer','Cloud Solution Engineer','Royal Bank of Canada','Toronto, ON, Canada','6 days ago');
INSERT INTO jobs VALUES(182,'Cloud Engineer','AWS Cloud Engineer','Thoughtworks','Toronto, ON, Canada','17 days ago');
INSERT INTO jobs VALUES(183,'Cloud Engineer','Azure Cloud Engineer','EY','Toronto, ON, Canada','24 days ago');
INSERT INTO jobs VALUES(184,'Cloud Engineer','OpenShift Cloud Engineer (6 Months Contract)','BDO Canada','Oakville, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(185,'Cloud Engineer','GCP Cloud engineer','ARROWMINDS INC','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(186,'Cloud Engineer','Senior Cloud Developer','Royal Bank of Canada','Toronto, ON, Canada','4 days ago');
INSERT INTO jobs VALUES(187,'Cloud Engineer','Network Cloud Engineer','Cognizant','Brampton, ON, Canada','28 days ago');
INSERT INTO jobs VALUES(188,'Cloud Engineer','Cloud Solution Engineer','Royal Bank of Canada','Calgary, AB, Canada','2 days ago');
INSERT INTO jobs VALUES(189,'Cloud Engineer','Cloud Engineer I','Paymentus (Canada) Corporation','Richmond Hill, ON, Canada','');
INSERT INTO jobs VALUES(190,'Cloud Engineer','Cloud Systems Engineer','PartnerRe','Toronto, ON, Canada','16 days ago');
INSERT INTO jobs VALUES(191,'Application Security Engineer','Senior Application Security Engineer','Ouster','Ottawa, ON, Canada','');
INSERT INTO jobs VALUES(192,'Application Security Engineer','Application Security Engineer, ETSE','Amazon','Vancouver, BC, Canada','22 days ago');
INSERT INTO jobs VALUES(193,'Application Security Engineer','Application Security Engineer','Agoda','Vancouver, BC, Canada','20 days ago');
INSERT INTO jobs VALUES(194,'Application Security Engineer','Application Security Engineer','Kraken Crypto Exchange','New Canada, NS, Canada','');
INSERT INTO jobs VALUES(195,'Application Security Engineer','Sr. Lead Application Security Engineer\u202f - Generative AI (Remote)','S&P Global','Victoria, BC, Canada','7 days ago');
INSERT INTO jobs VALUES(196,'Application Security Engineer','Senior Application Security Engineer','Score Media and Gaming Inc.','Canada','26 days ago');
INSERT INTO jobs VALUES(197,'Application Security Engineer','Sr. Application Security Specialist-Java (GCS)','Royal Bank of Canada','Vancouver, BC, Canada','3 days ago');
INSERT INTO jobs VALUES(198,'Application Security Engineer','Principal Security Engineer - Application Security','Gusto','Toronto, ON, Canada','20 days ago');
INSERT INTO jobs VALUES(199,'Application Security Engineer','Senior Application Security Engineer, ETSE','Amazon','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES(200,'Application Security Engineer','Field Application Engineer','McAfee','Waterloo, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(201,'Senior Web Developer','Senior Web Developer','Autodesk','Montreal, Quebec, Canada','20 days ago');
INSERT INTO jobs VALUES(202,'Senior Web Developer','Web Software Developer - Front End (Senior)','dakis','Montreal, Quebec, Canada','3 days ago');
INSERT INTO jobs VALUES(203,'Senior Web Developer','Senior Full Stack Web Developer','Epic Games','British Columbia, Canada','17 days ago');
INSERT INTO jobs VALUES(204,'Senior Web Developer','Senior Website Software Development Engineer','Advanced Micro Devices, Inc','Vancouver, BC, Canada','11 days ago');
INSERT INTO jobs VALUES(205,'Senior Web Developer','[Wattpad] Senior Web Engineer','WEBTOON Entertainment Inc. (Wattpad & WEBTOON Family of Brands)','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(206,'Senior Web Developer','Senior Full Stack Web Developer (Job Req #2024-285)','Ross Video','Ottawa, ON, Canada','16 days ago');
INSERT INTO jobs VALUES(207,'Senior Web Developer','Senior Full Stack Web Developer','TM8','Vancouver, BC, Canada','7 days ago');
INSERT INTO jobs VALUES(208,'Senior Web Developer','Senior Web Developer','Voices','Waterloo, ON, Canada','9 days ago');
INSERT INTO jobs VALUES(209,'Senior Web Developer','Senior Web Designer','Musora Media','Abbotsford, BC, Canada','9 days ago');
INSERT INTO jobs VALUES(210,'Senior Web Developer','Sr. Web Developer - AEC Integration','Esri','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(211,'php_developer','Senior Full-Stack PHP Developer, Services','Equisoft','Montreal, Quebec, Canada','');
INSERT INTO jobs VALUES(212,'php_developer','PHP Web Developer','WHC Online Solutions Inc.','Montreal, Quebec, Canada','');
INSERT INTO jobs VALUES(213,'php_developer','PHP Developers Canada','Kovasys','Canada','');
INSERT INTO jobs VALUES(214,'php_developer','Full-stack PHP developer','Graphically Speaking','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES(215,'php_developer','Senior PHP Developer','Software International','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(216,'php_developer','Senior PHP Application Developer � CONTRACT','Ward Technology Talent','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(217,'php_developer','PHP Web Developer � Toronto,ON','Kovasys','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(218,'php_developer','PHP Developer','CB Canada','Markham, ON, Canada','');
INSERT INTO jobs VALUES(219,'php_developer','PHP Developer','Priyasoft Inc.','Brampton, ON, Canada','29 days ago');
INSERT INTO jobs VALUES(220,'php_developer','Canada: Intermediate PHP Developer (CANAD004002)','ScanSource Canada Inc.','Alberta, Canada','');
INSERT INTO jobs VALUES(221,'Security Engineer','AWS Security Engineer','ProHire solutions','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(222,'Security Engineer','Information Security Engineer','CloudVital','Mississauga, ON, Canada','4 days ago');
INSERT INTO jobs VALUES(223,'Security Engineer','Cloud Security Engineer, Deloitte Global Technology','Deloitte','Toronto, ON, Canada','19 days ago');
INSERT INTO jobs VALUES(224,'Security Engineer','Senior Security Detection Engineer (GCS)','Royal Bank of Canada','Vancouver, BC, Canada','14 days ago');
INSERT INTO jobs VALUES(225,'Security Engineer','Intermediate Security Engineer, Corporate Security','GitLab','Canada','18 days ago');
INSERT INTO jobs VALUES(226,'Security Engineer','Senior Security Engineer','Dremio','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(227,'Security Engineer','Lead Security Engineer, Identity and Access Management','CPP Investments','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(228,'Security Engineer','Intermediate Security Engineer, Corporate Security','GitLab','United States','19 days ago');
INSERT INTO jobs VALUES(229,'Security Engineer','Sr. Ruby on Rails Engineer (Security)','Aha!','Halifax, NS, Canada','20 hours ago');
INSERT INTO jobs VALUES(230,'Security Engineer','Security Engineer - Encryption Engineer','TD Bank','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(231,'Devops Engineer','AWS DevOps Engineer','Group Nine LLC','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES(232,'Devops Engineer','Senior DevOps Engineer - Canada','SysAid Technologies','Toronto, ON, Canada','4 days ago');
INSERT INTO jobs VALUES(233,'Devops Engineer','DevOps Engineer','Zurich Insurance Company Ltd.','Toronto, ON, Canada','19 days ago');
INSERT INTO jobs VALUES(234,'Devops Engineer','Azure DevOps Engineer - Tech Lead','Lumenalta','Canada','2 hours ago');
INSERT INTO jobs VALUES(235,'Devops Engineer','DevOps and Platforms Engineer','Royal Bank of Canada','Toronto, ON, Canada','21 days ago');
INSERT INTO jobs VALUES(236,'Devops Engineer','DevOps Developer','Newfound Recruiting','Ottawa, ON, Canada','2 days ago');
INSERT INTO jobs VALUES(237,'Devops Engineer','Senior DevOps Engineer (Senior Engineer)','NielsenIQ','Toronto, ON, Canada','10 days ago');
INSERT INTO jobs VALUES(238,'Devops Engineer','Senior DevOps Engineer','Coconut Software','Saskatoon, SK, Canada','');
INSERT INTO jobs VALUES(239,'Devops Engineer','DevOps Engineer','Randstad Canada','Victoria, BC, Canada','5 days ago');
INSERT INTO jobs VALUES(240,'Devops Engineer','DevOps Engineer','Quarterhill','Saskatoon, SK, Canada','20 days ago');
INSERT INTO jobs VALUES(241,'Business Intelligence Developer','Business Intelligence Analyst/Developer','Acunor','Toronto, ON, Canada','19 days ago');
INSERT INTO jobs VALUES(242,'Business Intelligence Developer','Business Intelligence Developer (RFT 1.0 FTE)','The Royal','Ottawa, ON, Canada','');
INSERT INTO jobs VALUES(243,'Business Intelligence Developer','Business Intelligence & Reporting Developer','Husky Technologies','Bolton, ON, Canada','9 days ago');
INSERT INTO jobs VALUES(244,'Business Intelligence Developer','Business Intelligence Developer (12-Month contract)','Citco','Toronto, ON, Canada','1 month ago');
INSERT INTO jobs VALUES(245,'Business Intelligence Developer','BI Developer or Business Intelligence Developer','TalentBurst Inc','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES(246,'Business Intelligence Developer','Senior Business Intelligence Developer','FGF Brands','Canada','19 days ago');
INSERT INTO jobs VALUES(247,'Business Intelligence Developer','Business Intelligence Developer','Cineplex','Hunter River, PE, Canada','15 days ago');
INSERT INTO jobs VALUES(248,'Business Intelligence Developer','Senior Business Intelligence Consultant/Developer','Alphabyte','Toronto, ON, Canada','9 days ago');
INSERT INTO jobs VALUES(249,'Business Intelligence Developer','Senior BI Developer, Lead Looker Developer','Bitstrapped Inc','Toronto, ON, Canada','');
INSERT INTO jobs VALUES(250,'Business Intelligence Developer','BI & Data Visualization Developer','McAfee, LLC','Canada','5 days ago');

# DROP TABLE if EXISTS jobSkills;

CREATE TABLE jobSkills
(job_id INT PRIMARY KEY,
 skill_id INT
);



DROP TABLE IF EXISTS skills;

CREATE TABLE skills
(skill_id INT PRIMARY KEY,
 skill_name varchar(50)
);

INSERT INTO skills VALUES(0,'Python');
INSERT INTO skills VALUES(1,'Java');
INSERT INTO skills VALUES(2,'C++');
INSERT INTO skills VALUES(3,'C#');
INSERT INTO skills VALUES(4,'Go');
INSERT INTO skills VALUES(5,'Ruby');
INSERT INTO skills VALUES(6,'Swift');
INSERT INTO skills VALUES(7,'JavaScript');
INSERT INTO skills VALUES(8,'TypeScript');
INSERT INTO skills VALUES(9,'HTML');
INSERT INTO skills VALUES(10,'CSS');
INSERT INTO skills VALUES(11,'PHP');
INSERT INTO skills VALUES(12,'C');
INSERT INTO skills VALUES(13,'Rust');
INSERT INTO skills VALUES(14,'Assembly');
INSERT INTO skills VALUES(15,'Haskell');
INSERT INTO skills VALUES(16,'Scala');
INSERT INTO skills VALUES(17,'F#');
INSERT INTO skills VALUES(18,'Bash');
INSERT INTO skills VALUES(19,'PowerShell');
INSERT INTO skills VALUES(20,'Perl');
INSERT INTO skills VALUES(21,'SQL');
INSERT INTO skills VALUES(22,'R');
INSERT INTO skills VALUES(23,'MATLAB');
INSERT INTO skills VALUES(24,'Kotlin');
INSERT INTO skills VALUES(25,'Objective-C');
INSERT INTO skills VALUES(26,'Writing clean, maintainable, and scalable code');
INSERT INTO skills VALUES(27,'Debugging and troubleshooting');
INSERT INTO skills VALUES(28,'Adherence to coding standards and design patterns');
INSERT INTO skills VALUES(29,'Git');
INSERT INTO skills VALUES(30,'GitHub');
INSERT INTO skills VALUES(31,'GitLab');
INSERT INTO skills VALUES(32,'Bitbucket');
INSERT INTO skills VALUES(33,'SVN');
INSERT INTO skills VALUES(34,'Mercurial');
INSERT INTO skills VALUES(35,'Object-Oriented Design');
INSERT INTO skills VALUES(36,'System design and architecture');
INSERT INTO skills VALUES(37,'SOLID principles');
INSERT INTO skills VALUES(38,'Unit testing');
INSERT INTO skills VALUES(39,'JUnit');
INSERT INTO skills VALUES(40,'pytest');
INSERT INTO skills VALUES(41,'Mocha');
INSERT INTO skills VALUES(42,'Integration and functional testing');
INSERT INTO skills VALUES(43,'Test automation tools');
INSERT INTO skills VALUES(44,'Selenium');
INSERT INTO skills VALUES(45,'Cypress');
INSERT INTO skills VALUES(46,'TDD');
INSERT INTO skills VALUES(47,'BDD');
INSERT INTO skills VALUES(48,'Technical documentation');
INSERT INTO skills VALUES(49,'Markdown');
INSERT INTO skills VALUES(50,'Confluence');
INSERT INTO skills VALUES(51,'Swagger');
INSERT INTO skills VALUES(52,'OpenAPI');
INSERT INTO skills VALUES(53,'React');
INSERT INTO skills VALUES(54,'Angular');
INSERT INTO skills VALUES(55,'Vue.js');
INSERT INTO skills VALUES(56,'Svelte');
INSERT INTO skills VALUES(57,'Bootstrap');
INSERT INTO skills VALUES(58,'TailwindCSS');
INSERT INTO skills VALUES(59,'Material-UI');
INSERT INTO skills VALUES(60,'Node.js');
INSERT INTO skills VALUES(61,'Express');
INSERT INTO skills VALUES(62,'Django');
INSERT INTO skills VALUES(63,'Flask');
INSERT INTO skills VALUES(64,'Ruby on Rails');
INSERT INTO skills VALUES(65,'Spring Boot');
INSERT INTO skills VALUES(66,'ASP.NET Core');
INSERT INTO skills VALUES(67,'Flutter');
INSERT INTO skills VALUES(68,'React Native');
INSERT INTO skills VALUES(69,'Android SDK');
INSERT INTO skills VALUES(70,'iOS SDK');
INSERT INTO skills VALUES(71,'TensorFlow');
INSERT INTO skills VALUES(72,'PyTorch');
INSERT INTO skills VALUES(73,'Scikit-learn');
INSERT INTO skills VALUES(74,'Pandas');
INSERT INTO skills VALUES(75,'NumPy');
INSERT INTO skills VALUES(76,'Matplotlib');
INSERT INTO skills VALUES(77,'D3.js');
INSERT INTO skills VALUES(78,'Unity');
INSERT INTO skills VALUES(79,'Unreal Engine');
INSERT INTO skills VALUES(80,'Godot');
INSERT INTO skills VALUES(81,'CryEngine');
INSERT INTO skills VALUES(82,'MySQL');
INSERT INTO skills VALUES(83,'PostgreSQL');
INSERT INTO skills VALUES(84,'MariaDB');
INSERT INTO skills VALUES(85,'Oracle DB');
INSERT INTO skills VALUES(86,'Microsoft SQL Server');
INSERT INTO skills VALUES(87,'MongoDB');
INSERT INTO skills VALUES(88,'CouchDB');
INSERT INTO skills VALUES(89,'Firebase');
INSERT INTO skills VALUES(90,'DynamoDB');
INSERT INTO skills VALUES(91,'Cassandra');
INSERT INTO skills VALUES(92,'Neo4j');
INSERT INTO skills VALUES(93,'Amazon Neptune');
INSERT INTO skills VALUES(94,'Elasticsearch');
INSERT INTO skills VALUES(95,'Solr');
INSERT INTO skills VALUES(96,'Docker');
INSERT INTO skills VALUES(97,'Kubernetes');
INSERT INTO skills VALUES(98,'Jenkins');
INSERT INTO skills VALUES(99,'Travis CI');
INSERT INTO skills VALUES(100,'CircleCI');
INSERT INTO skills VALUES(101,'GitHub Actions');
INSERT INTO skills VALUES(102,'AWS');
INSERT INTO skills VALUES(103,'Azure');
INSERT INTO skills VALUES(104,'Google Cloud');
INSERT INTO skills VALUES(105,'Heroku');
INSERT INTO skills VALUES(106,'DigitalOcean');
INSERT INTO skills VALUES(107,'Terraform');
INSERT INTO skills VALUES(108,'Ansible');
INSERT INTO skills VALUES(109,'CloudFormation');
INSERT INTO skills VALUES(110,'Prometheus');
INSERT INTO skills VALUES(111,'Grafana');
INSERT INTO skills VALUES(112,'Splunk');
INSERT INTO skills VALUES(113,'ELK stack');
INSERT INTO skills VALUES(114,'OWASP principles');
INSERT INTO skills VALUES(115,'Metasploit');
INSERT INTO skills VALUES(116,'Burp Suite');
INSERT INTO skills VALUES(117,'Secure coding practices');
INSERT INTO skills VALUES(118,'TLS');
INSERT INTO skills VALUES(119,'SSL');
INSERT INTO skills VALUES(120,'RSA');
INSERT INTO skills VALUES(121,'AES');
INSERT INTO skills VALUES(122,'Problem-solving and algorithmic thinking');
INSERT INTO skills VALUES(123,'Communication and collaboration');
INSERT INTO skills VALUES(124,'Scrum');
INSERT INTO skills VALUES(125,'Kanban');
INSERT INTO skills VALUES(126,'Time management');
INSERT INTO skills VALUES(127,'Prioritization');
INSERT INTO skills VALUES(128,'Visual Studio Code');
INSERT INTO skills VALUES(129,'IntelliJ IDEA');
INSERT INTO skills VALUES(130,'Eclipse');
INSERT INTO skills VALUES(131,'PyCharm');
INSERT INTO skills VALUES(132,'Vim');
INSERT INTO skills VALUES(133,'Sublime Text');
INSERT INTO skills VALUES(134,'Jira');
INSERT INTO skills VALUES(135,'Trello');
INSERT INTO skills VALUES(136,'Asana');
INSERT INTO skills VALUES(137,'Postman');
INSERT INTO skills VALUES(138,'Insomnia');
INSERT INTO skills VALUES(139,'Figma');
INSERT INTO skills VALUES(140,'Adobe XD');
INSERT INTO skills VALUES(141,'Sketch');
INSERT INTO skills VALUES(142,'Tableau');
INSERT INTO skills VALUES(143,'Power BI');
INSERT INTO skills VALUES(144,'Ethereum');
INSERT INTO skills VALUES(145,'Solidity');
INSERT INTO skills VALUES(146,'Artificial Intelligence');
INSERT INTO skills VALUES(147,'Machine Learning');
INSERT INTO skills VALUES(148,'Internet of Things');
INSERT INTO skills VALUES(149,'Augmented Reality');
INSERT INTO skills VALUES(150,'Virtual Reality');
INSERT INTO skills VALUES(151,'Hadoop');
INSERT INTO skills VALUES(152,'Apache Spark');
INSERT INTO skills VALUES(153,'Kafka');
INSERT INTO skills VALUES(154,'Arduino');
INSERT INTO skills VALUES(155,'Raspberry Pi');
INSERT INTO skills VALUES(156,'RTOS');
INSERT INTO skills VALUES(157,'TCP/IP');
INSERT INTO skills VALUES(158,'UDP');
INSERT INTO skills VALUES(159,'Network security');
INSERT INTO skills VALUES(160,'Qiskit');
INSERT INTO skills VALUES(161,'IBM Q Experience');


# INSERT INTO privateOwner VALUES('CO46','Joe','Keogh','2 Fergus Dr. Aberdeen AB2 ','01224-861212', 'jkeogh@lhh.com', null);
# INSERT INTO privateOwner VALUES('CO87','Carol','Farrel','6 Achray St. Glasgow G32 9DX','0141-357-7419', 'cfarrel@gmail.com', null);
# INSERT INTO privateOwner VALUES('CO40','Tina','Murphy','63 Well St. Glasgow G42','0141-943-1728', 'tinam@hotmail.com', null);
# INSERT INTO privateOwner VALUES('CO93','Tony','Shaw','12 Park Pl. Glasgow G4 0QR','0141-225-7025', 'tony.shaw@ark.com', null);

DROP TABLE IF EXISTS jobProviders;
CREATE TABLE jobProviders
(job_id INT PRIMARY KEY,
 skill_id INT
);

# INSERT INTO propertyForRent VALUES('PA14','16 Holhead','Aberdeen','AB7 5SU','House',6,650,'CO46','SA9','B007');
# INSERT INTO propertyForRent VALUES('PL94','6 Argyll St','London','NW2','Flat',4,400,'CO87','SL41','B005' );
# INSERT INTO propertyForRent VALUES('PG4','6 Lawrence St','Glasgow','G11 9QX','Flat',3,350,'CO40', NULL, 'B003');
# INSERT INTO propertyForRent VALUES('PG36','2 Manor Rd','Glasgow','G32 4QX','Flat',3,375,'CO93','SG37','B003' );
# INSERT INTO propertyForRent VALUES('PG21','18 Dale Rd','Glasgow','G12','House',5,600,'CO87','SG37','B003');
# INSERT INTO propertyForRent VALUES('PG16','5 Novar Dr','Glasgow','G12 9AX','Flat',4,450,'CO93','SG14','B003' );

DROP TABLE IF EXISTS providers;
CREATE TABLE providers
(provider_id INT PRIMARY KEY,
 provider_site varchar(100)
);

# INSERT INTO client VALUES('CR76','John','Kay','0171-774-5632','Flat',425, 'john.kay@gmail.com');
# INSERT INTO client VALUES('CR56','Aline','Steward','0141-848-1825','Flat',350, 'astewart@hotmail.com');
# INSERT INTO client VALUES('CR74','Mike','Ritchie','01475-943-1728','House',750, 'mritchie@yahoo.co.uk');
# INSERT INTO client VALUES('CR62','Mary','Tregear','01224-196720','Flat',600, 'maryt@hotmail.co.uk');

# DROP TABLE IF EXISTS viewing;
# CREATE TABLE  viewing
# (clientNo char(5) not null,
#  propertyNo char(5) not null,
#  viewDate date,
#  comment_ varchar(15)
# );
# INSERT INTO viewing VALUES('CR56','PA14','2015-05-24','too small');
# INSERT INTO viewing VALUES('CR76','PG4','2015-04-20','too remote');
# INSERT INTO viewing VALUES('CR56','PG4','2015-05-26',null);
# INSERT INTO viewing VALUES('CR62','PA14','2015-05-14','no dining room');
# INSERT INTO viewing VALUES('CR56','PG36','2015-04-28',null);

# DROP TABLE IF EXISTS registration;
# CREATE TABLE registration
# (clientNo char(5) not null,
#  branchNo char(5) not null,
#  staffNo char(5) not null,
#  dateJoined date
# );

# INSERT INTO registration VALUES('CR76','B005','SL41','2015-01-13');
# INSERT INTO registration VALUES('CR56','B003','SG37','2014-04-13');
# INSERT INTO registration VALUES('CR74','B003','SG37','2013-11-16');
# INSERT INTO registration VALUES('CR62','B007','SA9','2014-03-07');
