INSERT INTO skills VALUES('Python',0);
INSERT INTO skills VALUES('Java',1);
INSERT INTO skills VALUES('C++',2);
INSERT INTO skills VALUES('C#',3);
INSERT INTO skills VALUES('Go',4);
INSERT INTO skills VALUES('Ruby',5);
INSERT INTO skills VALUES('Swift',6);
INSERT INTO skills VALUES('JavaScript',7);
INSERT INTO skills VALUES('TypeScript',8);
INSERT INTO skills VALUES('HTML',9);
INSERT INTO skills VALUES('CSS',10);
INSERT INTO skills VALUES('PHP',11);
INSERT INTO skills VALUES('C',12);
INSERT INTO skills VALUES('Rust',13);
INSERT INTO skills VALUES('Assembly',14);
INSERT INTO skills VALUES('Haskell',15);
INSERT INTO skills VALUES('Scala',16);
INSERT INTO skills VALUES('F#',17);
INSERT INTO skills VALUES('Bash',18);
INSERT INTO skills VALUES('PowerShell',19);
INSERT INTO skills VALUES('Perl',20);
INSERT INTO skills VALUES('SQL',21);
INSERT INTO skills VALUES('R',22);
INSERT INTO skills VALUES('MATLAB',23);
INSERT INTO skills VALUES('Kotlin',24);
INSERT INTO skills VALUES('Objective-C',25);
INSERT INTO skills VALUES('Writing clean, maintainable, and scalable code',26);
INSERT INTO skills VALUES('Debugging and troubleshooting',27);
INSERT INTO skills VALUES('Adherence to coding standards and design patterns',28);
INSERT INTO skills VALUES('Git',29);
INSERT INTO skills VALUES('GitHub',30);
INSERT INTO skills VALUES('GitLab',31);
INSERT INTO skills VALUES('Bitbucket',32);
INSERT INTO skills VALUES('SVN',33);
INSERT INTO skills VALUES('Mercurial',34);
INSERT INTO skills VALUES('Object-Oriented Design',35);
INSERT INTO skills VALUES('System design and architecture',36);
INSERT INTO skills VALUES('SOLID principles',37);
INSERT INTO skills VALUES('Unit testing',38);
INSERT INTO skills VALUES('JUnit',39);
INSERT INTO skills VALUES('pytest',40);
INSERT INTO skills VALUES('Mocha',41);
INSERT INTO skills VALUES('Integration and functional testing',42);
INSERT INTO skills VALUES('Test automation tools',43);
INSERT INTO skills VALUES('Selenium',44);
INSERT INTO skills VALUES('Cypress',45);
INSERT INTO skills VALUES('TDD',46);
INSERT INTO skills VALUES('BDD',47);
INSERT INTO skills VALUES('Technical documentation',48);
INSERT INTO skills VALUES('Markdown',49);
INSERT INTO skills VALUES('Confluence',50);
INSERT INTO skills VALUES('Swagger',51);
INSERT INTO skills VALUES('OpenAPI',52);
INSERT INTO skills VALUES('React',53);
INSERT INTO skills VALUES('Angular',54);
INSERT INTO skills VALUES('Vue.js',55);
INSERT INTO skills VALUES('Svelte',56);
INSERT INTO skills VALUES('Bootstrap',57);
INSERT INTO skills VALUES('TailwindCSS',58);
INSERT INTO skills VALUES('Material-UI',59);
INSERT INTO skills VALUES('Node.js',60);
INSERT INTO skills VALUES('Express',61);
INSERT INTO skills VALUES('Django',62);
INSERT INTO skills VALUES('Flask',63);
INSERT INTO skills VALUES('Ruby on Rails',64);
INSERT INTO skills VALUES('Spring Boot',65);
INSERT INTO skills VALUES('ASP.NET Core',66);
INSERT INTO skills VALUES('Flutter',67);
INSERT INTO skills VALUES('React Native',68);
INSERT INTO skills VALUES('Android SDK',69);
INSERT INTO skills VALUES('iOS SDK',70);
INSERT INTO skills VALUES('TensorFlow',71);
INSERT INTO skills VALUES('PyTorch',72);
INSERT INTO skills VALUES('Scikit-learn',73);
INSERT INTO skills VALUES('Pandas',74);
INSERT INTO skills VALUES('NumPy',75);
INSERT INTO skills VALUES('Matplotlib',76);
INSERT INTO skills VALUES('D3.js',77);
INSERT INTO skills VALUES('Unity',78);
INSERT INTO skills VALUES('Unreal Engine',79);
INSERT INTO skills VALUES('Godot',80);
INSERT INTO skills VALUES('CryEngine',81);
INSERT INTO skills VALUES('MySQL',82);
INSERT INTO skills VALUES('PostgreSQL',83);
INSERT INTO skills VALUES('MariaDB',84);
INSERT INTO skills VALUES('Oracle DB',85);
INSERT INTO skills VALUES('Microsoft SQL Server',86);
INSERT INTO skills VALUES('MongoDB',87);
INSERT INTO skills VALUES('CouchDB',88);
INSERT INTO skills VALUES('Firebase',89);
INSERT INTO skills VALUES('DynamoDB',90);
INSERT INTO skills VALUES('Cassandra',91);
INSERT INTO skills VALUES('Neo4j',92);
INSERT INTO skills VALUES('Amazon Neptune',93);
INSERT INTO skills VALUES('Elasticsearch',94);
INSERT INTO skills VALUES('Solr',95);
INSERT INTO skills VALUES('Docker',96);
INSERT INTO skills VALUES('Kubernetes',97);
INSERT INTO skills VALUES('Jenkins',98);
INSERT INTO skills VALUES('Travis CI',99);
INSERT INTO skills VALUES('CircleCI',100);
INSERT INTO skills VALUES('GitHub Actions',101);
INSERT INTO skills VALUES('AWS',102);
INSERT INTO skills VALUES('Azure',103);
INSERT INTO skills VALUES('Google Cloud',104);
INSERT INTO skills VALUES('Heroku',105);
INSERT INTO skills VALUES('DigitalOcean',106);
INSERT INTO skills VALUES('Terraform',107);
INSERT INTO skills VALUES('Ansible',108);
INSERT INTO skills VALUES('CloudFormation',109);
INSERT INTO skills VALUES('Prometheus',110);
INSERT INTO skills VALUES('Grafana',111);
INSERT INTO skills VALUES('Splunk',112);
INSERT INTO skills VALUES('ELK stack',113);
INSERT INTO skills VALUES('OWASP principles',114);
INSERT INTO skills VALUES('Metasploit',115);
INSERT INTO skills VALUES('Burp Suite',116);
INSERT INTO skills VALUES('Secure coding practices',117);
INSERT INTO skills VALUES('TLS',118);
INSERT INTO skills VALUES('SSL',119);
INSERT INTO skills VALUES('RSA',120);
INSERT INTO skills VALUES('AES',121);
INSERT INTO skills VALUES('Problem-solving and algorithmic thinking',122);
INSERT INTO skills VALUES('Communication and collaboration',123);
INSERT INTO skills VALUES('Scrum',124);
INSERT INTO skills VALUES('Kanban',125);
INSERT INTO skills VALUES('Time management',126);
INSERT INTO skills VALUES('Prioritization',127);
INSERT INTO skills VALUES('Visual Studio Code',128);
INSERT INTO skills VALUES('IntelliJ IDEA',129);
INSERT INTO skills VALUES('Eclipse',130);
INSERT INTO skills VALUES('PyCharm',131);
INSERT INTO skills VALUES('Vim',132);
INSERT INTO skills VALUES('Sublime Text',133);
INSERT INTO skills VALUES('Jira',134);
INSERT INTO skills VALUES('Trello',135);
INSERT INTO skills VALUES('Asana',136);
INSERT INTO skills VALUES('Postman',137);
INSERT INTO skills VALUES('Insomnia',138);
INSERT INTO skills VALUES('Figma',139);
INSERT INTO skills VALUES('Adobe XD',140);
INSERT INTO skills VALUES('Sketch',141);
INSERT INTO skills VALUES('Tableau',142);
INSERT INTO skills VALUES('Power BI',143);
INSERT INTO skills VALUES('Ethereum',144);
INSERT INTO skills VALUES('Solidity',145);
INSERT INTO skills VALUES('Artificial Intelligence',146);
INSERT INTO skills VALUES('Machine Learning',147);
INSERT INTO skills VALUES('Internet of Things',148);
INSERT INTO skills VALUES('Augmented Reality',149);
INSERT INTO skills VALUES('Virtual Reality',150);
INSERT INTO skills VALUES('Hadoop',151);
INSERT INTO skills VALUES('Apache Spark',152);
INSERT INTO skills VALUES('Kafka',153);
INSERT INTO skills VALUES('Arduino',154);
INSERT INTO skills VALUES('Raspberry Pi',155);
INSERT INTO skills VALUES('RTOS',156);
INSERT INTO skills VALUES('TCP/IP',157);
INSERT INTO skills VALUES('UDP',158);
INSERT INTO skills VALUES('Network security',159);
INSERT INTO skills VALUES('Qiskit',160);
INSERT INTO skills VALUES('IBM Q Experience',161);
