INSERT INTO jobs VALUES('Full-Stack\u202f.NET\u202fDeveloper\u202f(Web & Desktop)','full_stack_developer',1,'Whitecap Canada','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Java Full Stack Developer (Angular/React) - Hybrid','full_stack_developer',2,'Cognizant','Ontario, Canada','5 days ago');
INSERT INTO jobs VALUES('Senior Full Stack Developer','full_stack_developer',3,'Royal Bank of Canada','Calgary, AB, Canada','14 days ago');
INSERT INTO jobs VALUES('Full-Stack Developer','full_stack_developer',4,'DLL','Burlington, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Fullstack Developer','full_stack_developer',5,'Citi','Mississauga, ON, Canada','');
INSERT INTO jobs VALUES('Full Stack Developer','full_stack_developer',6,'Accenture','Montreal, Quebec, Canada','');
INSERT INTO jobs VALUES('full stack developer','full_stack_developer',7,'SPRH CONSULTING INC.','Oshawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Junior Full-Stack Developer','full_stack_developer',8,'Q Wealth Partners','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Intermediate Full Stack Developer','full_stack_developer',9,'Hitachi Careers','Toronto, ON, Canada','19 days ago');
INSERT INTO jobs VALUES('Senior Full Stack Developer (Bilingual - French/English)','full_stack_developer',10,'Graphem Solutions','Burnaby, BC, Canada','20 hours ago');
INSERT INTO jobs VALUES('Software Engineer, Banking Technology','software_engineer',11,'Manulife','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Software Engineer (Full-Stack)','software_engineer',12,'Mastercard','Vancouver, BC, Canada','9 days ago');
INSERT INTO jobs VALUES('Software Developer 2','software_engineer',13,'Intuit','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Online Software Engineer','software_engineer',14,'Electronic Arts (EA)','Burnaby, BC, Canada','5 days ago');
INSERT INTO jobs VALUES('Software Engineer (Onsite)','software_engineer',15,'RTX','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Sr. Software Engineer (Front End)','software_engineer',16,'McGraw Hill LLC.','Canada','');
INSERT INTO jobs VALUES('Software Engineer II (DevSecOps Engineer)','software_engineer',17,'Planview Incorporated','Vancouver, BC, Canada','27 days ago');
INSERT INTO jobs VALUES('Senior Staff Software Engineer','software_engineer',18,'Posting Date:07/ 08/2024','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Software Development Engineer','software_engineer',19,'Inkeros','Ontario, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Software Engineer','software_engineer',20,'Synopsys','Markham, ON, Canada','19 days ago');
INSERT INTO jobs VALUES('Senior Software Engineer (Full-Stack)','senior_software_engineer',21,'Mastercard','Vancouver, BC, Canada','9 days ago');
INSERT INTO jobs VALUES('Senior Software Engineer','senior_software_engineer',22,'MEDA Group','Waterloo, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Software Engineer, Data Platform','senior_software_engineer',23,'Coinbase','Victoria, BC, Canada','9 hours ago');
INSERT INTO jobs VALUES('Sr Software Engineer- Remote','senior_software_engineer',24,'BeyondTrust','British Columbia, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Software Engineer','senior_software_engineer',25,'Synopsys','Markham, ON, Canada','19 days ago');
INSERT INTO jobs VALUES('Sr Software Developer','senior_software_engineer',26,'WARNERMEDIA','Kanata, ON, Canada','20 days ago');
INSERT INTO jobs VALUES('Senior Staff Software Engineer','senior_software_engineer',27,'Posting Date:07/ 08/2024','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Remote Senior Software Engineer (Eastern Canada)','senior_software_engineer',28,'Centric Software','Canada','4 days ago');
INSERT INTO jobs VALUES('Senior Software Engineer (backend) - Toronto','senior_software_engineer',29,'Borderless AI','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Sr Software Engineer - Canada','senior_software_engineer',30,'Alstom','Toronto, ON, Canada','13 days ago');
INSERT INTO jobs VALUES('Front End Developer','front_end_developer',31,'Stebr Canada Inc.','Toronto, ON, Canada','6 days ago');
INSERT INTO jobs VALUES('Front End Engineer','front_end_developer',32,'Kiwee Intelligence Inc.','Canada','5 hours ago');
INSERT INTO jobs VALUES('Senior Frontend Developer','front_end_developer',33,'Royal Bank of Canada','Toronto, ON, Canada','20 days ago');
INSERT INTO jobs VALUES('Axiom - Front-End Developer','front_end_developer',34,'Equinox Engineering Ltd.','Calgary, AB, Canada','3 days ago');
INSERT INTO jobs VALUES('Web Software Developer - Front End (Senior)','front_end_developer',35,'dakis','Montreal, Quebec, Canada','3 days ago');
INSERT INTO jobs VALUES('UI Frontend Developer - EA SPORTS UFC','front_end_developer',36,'Electronic Arts (EA)','Burnaby, BC, Canada','2 days ago');
INSERT INTO jobs VALUES('Front End Developer','front_end_developer',37,'Compass Group Canada','Mississauga, ON, Canada','26 days ago');
INSERT INTO jobs VALUES('Frontend Developer','front_end_developer',38,'PDF Solutions','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES('Front-End Developer','front_end_developer',39,'BLAZESOFT','Vaughan, ON, Canada','');
INSERT INTO jobs VALUES('Front End and Full Stack Developer (Remote - Ontario, Canada ONLY)','front_end_developer',40,'Ample Insight Inc.','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Web developer','web_developer',41,'Compuran as well as ITD Canada','Vancouver, BC, Canada','3 days ago');
INSERT INTO jobs VALUES('Web Developer – Co-op/Intern','web_developer',42,'Nokia','Ontario, Canada','2 days ago');
INSERT INTO jobs VALUES('Web Developer','web_developer',43,'Design Shopp','Canada','');
INSERT INTO jobs VALUES('Web developer','web_developer',44,'webever technologies','Winnipeg, MB, Canada','3 days ago');
INSERT INTO jobs VALUES('Web Software Developer - Front End (Senior)','web_developer',45,'dakis','Montreal, Quebec, Canada','3 days ago');
INSERT INTO jobs VALUES('Java Web Developer','web_developer',46,'STACK IT Recruitment','Mississauga, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Software Developer (Back End Web Services)','web_developer',47,'Thales','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Web Designer & Developer','web_developer',48,'Apple Blueprints','Canada','1 month ago');
INSERT INTO jobs VALUES('front-end Web developer','web_developer',49,'SOFTRON TAX','Mississauga, ON, Canada','5 days ago');
INSERT INTO jobs VALUES('Front End Developer','web_developer',50,'Stebr Canada Inc.','Toronto, ON, Canada','6 days ago');
INSERT INTO jobs VALUES('AI Software Developer','developer',51,'Merck KGaA, Darmstadt, Germany','Montreal, Quebec, Canada','4 days ago');
INSERT INTO jobs VALUES('Software Developer - Senior','developer',52,'US Tech Solutions','Markham, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Software Developer 2','developer',53,'Intuit','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Software Developer II','developer',54,'WARNERMEDIA','Kanata, ON, Canada','1 month ago');
INSERT INTO jobs VALUES('Principle Software Developer - Montreal','developer',55,'Keywords Studios','Quebec, Canada','6 days ago');
INSERT INTO jobs VALUES('Software Developer III, AI/ML, Google Cloud AI','developer',56,'Google','Toronto, ON, Canada','4 days ago');
INSERT INTO jobs VALUES('Software Developer','developer',57,'L3Harris Technologies','Ottawa, ON, Canada','');
INSERT INTO jobs VALUES('Senior Full Stack Developer','developer',58,'Luxoft','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Senior Software Developer, GFT','developer',59,'Royal Bank of Canada','Vancouver, BC, Canada','4 days ago');
INSERT INTO jobs VALUES('Software Developer – Mobile','developer',60,'Evercommerce','Oakville, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Sr. Dot Net Developer','.net_developer',61,'Stellar Software Solutions','Halifax, NS, Canada','2 days ago');
INSERT INTO jobs VALUES('Dotnet Developer','.net_developer',62,'Diamondpick','Mississauga, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('.NET Developers','.net_developer',63,'Canada IT Club','Ontario, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior .NET Developer (Sitecore CMS)','.net_developer',64,'Canadian Cancer Society','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior .NET Developer','.net_developer',65,'Mariner Innovations','Fredericton, NB, Canada','5 days ago');
INSERT INTO jobs VALUES('Senior C#/.Net Developer','.net_developer',66,'Societe Generale','Montreal, Quebec, Canada','9 days ago');
INSERT INTO jobs VALUES('.NET Software Developer','.net_developer',67,'CB Canada','New Westminster, BC, Canada','');
INSERT INTO jobs VALUES('Developer Digital Development (.NET MAUI)','.net_developer',68,'Randstad','Toronto, ON, Canada','23 days ago');
INSERT INTO jobs VALUES('P2 - Full Stack Developer - .Net Core','.net_developer',69,'Randstad Canada','Mississauga, ON, Canada','');
INSERT INTO jobs VALUES('.Net Developer','.net_developer',70,'BlazeSoft','Vaughan, ON, Canada','');
INSERT INTO jobs VALUES('Junior Java Developer','java_developer',71,'Delbridge Solutions','Ontario, Canada','2 days ago');
INSERT INTO jobs VALUES('Java Developer','java_developer',72,'Scotiabank','Toronto, ON, Canada','5 days ago');
INSERT INTO jobs VALUES('Senior Java Developer','java_developer',73,'GFL Environmental Inc.','Vaughan, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Java Developer (GCP/AWS) - Contract - Toronto','java_developer',74,'CorGTA Inc.','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Core Java Developer','java_developer',75,'Iris Software Inc.','Toronto, ON, Canada','4 days ago');
INSERT INTO jobs VALUES('Senior Java Developer','java_developer',76,'Citi','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Java Web Developer','java_developer',77,'STACK IT Recruitment','Mississauga, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Java Developer','java_developer',78,'isgSearch','Vaughan, ON, Canada','6 days ago');
INSERT INTO jobs VALUES('Java Developer','java_developer',79,'Scotiabank','Toronto, ON, Canada','9 days ago');
INSERT INTO jobs VALUES('GTS - Sr. Java Developers ONLY Living outside of Canada- Work Visa Provided - CANADA','java_developer',80,'Venuiti','Waterloo, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('AI Application Developer – HYBRID (1684)','application_developer',81,'Direct IT Recruiting Inc., WBE Canada Certified','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Application Developer Microsoft Power Platform','application_developer',82,'Artech L.L.C.','Toronto, ON, Canada','6 days ago');
INSERT INTO jobs VALUES('Application Software Developer Lead - (Java / JSON/ AWS / IBM Websphere/ Payments)','application_developer',83,'Bank of Montreal','Toronto, ON, Canada','4 days ago');
INSERT INTO jobs VALUES('Software Developer 2','application_developer',84,'Intuit','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Application Developer II / Senior Software Engineer','application_developer',85,'Randstad','Toronto, ON, Canada','26 days ago');
INSERT INTO jobs VALUES('Applications Development Tech Lead','application_developer',86,'Citi','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Application Developer','application_developer',87,'Stantec','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES('Web Application Developer Canada','application_developer',88,'Backlight',"St. John's, NL, Canada",'');
INSERT INTO jobs VALUES('Web Application Developer','application_developer',89,'Celayix','Vancouver, BC, Canada','26 days ago');
INSERT INTO jobs VALUES('Software Developer II','application_developer',90,'WARNERMEDIA','Kanata, ON, Canada','1 month ago');
INSERT INTO jobs VALUES('Web Designer & Developer','web_designer',91,'Apple Blueprints','Canada','1 month ago');
INSERT INTO jobs VALUES('Freelance Website Designer','web_designer',92,'Websharx','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Product/Web Designer','web_designer',93,'OpusClip','Burnaby, BC, Canada','');
INSERT INTO jobs VALUES('Web designer','web_designer',94,'Canadawide Jobs Inc','Abbotsford, BC, Canada','');
INSERT INTO jobs VALUES('Web Designer','web_designer',95,'Newfound Recruiting','Ottawa, ON, Canada','9 days ago');
INSERT INTO jobs VALUES('Web Designer / Front-end Developer','web_designer',96,'Earth Rangers','Ontario, Canada','');
INSERT INTO jobs VALUES('Web designer','web_designer',97,'Immigration Canada Pro','Ontario, Canada','');
INSERT INTO jobs VALUES('Graphic & Web Designer','web_designer',98,'Kepler Canada','Richmond Hill, ON, Canada','27 days ago');
INSERT INTO jobs VALUES('Designer, Web Presence (Events)','web_designer',99,'Stripe','Toronto, ON, Canada','26 days ago');
INSERT INTO jobs VALUES('Web designer - graphic design','web_designer',100,'RIGHTMOVE DESIGN INC','Abbotsford, BC, Canada','');
INSERT INTO jobs VALUES('Senior Developer (ServiceNow and Power Platform)','senior_developer',101,'Hays','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Senior Software Developer','senior_developer',102,'D2L','Kitchener, ON, Canada','');
INSERT INTO jobs VALUES('Senior Software Developer, GFT','senior_developer',103,'Royal Bank of Canada','Vancouver, BC, Canada','4 days ago');
INSERT INTO jobs VALUES('Senior Frontend Developer','senior_developer',104,'Randstad Digital','Oakville, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Senior iOS Developer','senior_developer',105,'WARNERMEDIA','Kanata, ON, Canada','1 month ago');
INSERT INTO jobs VALUES('Software Developer - Senior','senior_developer',106,'US Tech Solutions','Markham, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Senior Developer (Kotlin)','senior_developer',107,'Thoughtworks','Toronto, ON, Canada','24 days ago');
INSERT INTO jobs VALUES('Senior Software Developer, 6+ years - Canada (Remote)','senior_developer',108,'Info-Tech Research Group','Toronto, ON, Canada','11 days ago');
INSERT INTO jobs VALUES('Sr. Software Engineer (Front End)','senior_developer',109,'McGraw Hill LLC.','Canada','');
INSERT INTO jobs VALUES('Senior Developer - Canada Wide - Remote','senior_developer',110,'Newton','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Principal Software Engineer Team Lead- Canada','principal_software_engineer',111,'Bellwood Labs','Toronto, ON, Canada','6 days ago');
INSERT INTO jobs VALUES('Senior Staff / Principal Software Developer','principal_software_engineer',112,'Intuit','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Principal Software Engineer','principal_software_engineer',113,'Microsoft','Vancouver, BC, Canada','11 days ago');
INSERT INTO jobs VALUES('Principal Software Engineering Manager - AI performance','principal_software_engineer',114,'Microsoft','Vancouver, BC, Canada','4 days ago');
INSERT INTO jobs VALUES('Principal Software Engineer 1 - Game of Thrones: Legends','principal_software_engineer',115,'Zynga','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Principal Software Engineer 2 - Game Services, ZGMT','principal_software_engineer',116,'Zynga','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Principal Software Engineer 1 – Game of Thrones: Legends','principal_software_engineer',117,'Zynga','Canada','3 days ago');
INSERT INTO jobs VALUES('Principal Software Engineer Team Lead','principal_software_engineer',118,'Bellwood','Canada','4 days ago');
INSERT INTO jobs VALUES('Principal Software Engineer - Data Platform','principal_software_engineer',119,'Toast','Canada','');
INSERT INTO jobs VALUES('Principal Software Engineer, AI/ML Platform','principal_software_engineer',120,'Autodesk','Toronto, ON, Canada','17 days ago');
INSERT INTO jobs VALUES('Backend Developer (Montreal Canada Only)','back_end_developer',121,'MagicPace','Montreal, Quebec, Canada','3 days ago');
INSERT INTO jobs VALUES('Software Developer (Back End Web Services)','back_end_developer',122,'Thales','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Back End Developer','back_end_developer',123,'Expansion','Vaughan, ON, Canada','24 days ago');
INSERT INTO jobs VALUES('Back End Developer','back_end_developer',124,'Boast','Vancouver, BC, Canada','2 days ago');
INSERT INTO jobs VALUES('Backend Developer - Canada','back_end_developer',125,'SysAid Technologies','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Lead Backend Developer','back_end_developer',126,'Royal Bank of Canada','Toronto, ON, Canada','12 days ago');
INSERT INTO jobs VALUES('Back End Developer','back_end_developer',127,'Robert Half','Toronto, ON, Canada','12 days ago');
INSERT INTO jobs VALUES('Azure Backend Developer-Canada','back_end_developer',128,'Zortech Solutions','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Java Back End Developer - IT (Information Technology) - Montreal, Canada','back_end_developer',129,'Societe Generale','Montreal, Quebec, Canada','');
INSERT INTO jobs VALUES('Backend Software Engineer - Cloud Traffic and Networking (Remote - Canada)','back_end_developer',130,'Confluent Career Site','Ontario, Canada','12 days ago');
INSERT INTO jobs VALUES('Senior .NET Developer','senior_.net_developer',131,'Mariner Innovations','Fredericton, NB, Canada','5 days ago');
INSERT INTO jobs VALUES('Senior .NET Developer','senior_.net_developer',132,'MDA Space','Sainte-Anne-de-Bellevue, Quebec, Canada','19 days ago');
INSERT INTO jobs VALUES('Senior .NET Developer (Sitecore CMS)','senior_.net_developer',133,'Canadian Cancer Society','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('.Net Developer','senior_.net_developer',134,'AdventInfotech','Ottawa, ON, Canada','6 days ago');
INSERT INTO jobs VALUES('Senior .NET Developer/Analyst','senior_.net_developer',135,'Agricorp','Guelph, ON, Canada','7 days ago');
INSERT INTO jobs VALUES('Senior .net developer to complete the rebuild of an existing software solution into a cloud agnostic application in the public sector.','senior_.net_developer',136,'S.i. Systems','Ottawa, ON, Canada','17 days ago');
INSERT INTO jobs VALUES('Senior Fullstack developer - Websites Connectivity','senior_.net_developer',137,'Coveo','New Canada, NS, Canada','');
INSERT INTO jobs VALUES('Senior Net Developer with Net core Angular 12 AND SQL AZURE','senior_.net_developer',138,'Purple Drive','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Canada: Sr API Developer (CANAD004085)','senior_.net_developer',139,'ScanSource','Calgary, AB, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Software Developer','senior_.net_developer',140,'D2L','Kitchener, ON, Canada','');
INSERT INTO jobs VALUES('Dow Canada Senior Engineer Opportunities','senior_engineer',141,'THE DOW CHEMICAL COMPANY','Penhold, AB, Canada','6 days ago');
INSERT INTO jobs VALUES('Senior Power Systems Engineer | Renewable Energy','senior_engineer',142,'Potenco','Ontario, Canada','4 days ago');
INSERT INTO jobs VALUES('Senior Structural Engineer','senior_engineer',143,'Madison Taylor Design','Midhurst, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Senior Bridge Engineer','senior_engineer',144,'Jacobs','Kitchener, ON, Canada','5 days ago');
INSERT INTO jobs VALUES('Senior Machine Learning Engineer','senior_engineer',145,'BenchSci','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Systems Engineer','senior_engineer',146,'Calian Group Ltd.','Ontario, Canada','');
INSERT INTO jobs VALUES('Senior II Electrical Engineer','senior_engineer',147,'MineSense Technologies Ltd.','Vancouver, BC, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Project Engineer','senior_engineer',148,'ABB','Quebec, Canada','25 days ago');
INSERT INTO jobs VALUES('Senior Artificial Intelligence Engineer ( Senior Data Scientist - AI)','senior_engineer',149,'Compass Group Canada','Mississauga, ON, Canada','4 days ago');
INSERT INTO jobs VALUES('Senior Software Engineer (Full-Stack)','senior_engineer',150,'Mastercard','Vancouver, BC, Canada','9 days ago');
INSERT INTO jobs VALUES('Senior Java Developer','senior_java_developer',151,'Citi','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Senior Java Developer','senior_java_developer',152,'GFL Environmental Inc.','Vaughan, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Senior Java Developer','senior_java_developer',153,'Citi','Mississauga, ON, Canada','');
INSERT INTO jobs VALUES('Senior Java Spark Bigdata Developer','senior_java_developer',154,'Citi','Mississauga, ON, Canada','');
INSERT INTO jobs VALUES('Senior Java Developer','senior_java_developer',155,'Fulcrum Digital Inc.','Victoria, BC, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Java Spring Boot Developer','senior_java_developer',156,'BrightOrder Inc.','Mississauga, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Java Spring Boot Developer','senior_java_developer',157,'BrightOrder Inc.','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Senior Java Backend Developer','senior_java_developer',158,'HCPL Global Inc.','Mississauga, ON, Canada','4 days ago');
INSERT INTO jobs VALUES('Senior Java Fullstack with React ( 70 % Backend + 30 % frontend )in','senior_java_developer',159,'Syntricate Technologies','Mississauga, ON, Canada','5 days ago');
INSERT INTO jobs VALUES('Senior Java Developer','senior_java_developer',160,'ICE','Calgary, AB, Canada','7 days ago');
INSERT INTO jobs VALUES('Software Developer - Senior','senior_application_developer',161,'US Tech Solutions','Markham, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Senior Software Application Engineer','senior_application_developer',162,'Quarry Consulting','Canada','4 days ago');
INSERT INTO jobs VALUES('Senior Software Developer (Halifax), GFT','senior_application_developer',163,'Royal Bank of Canada','Nova Scotia, Canada','11 days ago');
INSERT INTO jobs VALUES('Senior Software Engineer (Full Stack Developer)','senior_application_developer',164,'Tradable Bits','Vancouver, BC, Canada','16 days ago');
INSERT INTO jobs VALUES('Senior Full Stack Developer','senior_application_developer',165,'Luxoft','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Senior Software Engineer','senior_application_developer',166,'Synopsys','Markham, ON, Canada','19 days ago');
INSERT INTO jobs VALUES('Senior Analyst, Application Development and Maintenance','senior_application_developer',167,'Air Canada','Dorval, Quebec, Canada','');
INSERT INTO jobs VALUES('Senior Software Developer (C#), GFT','senior_application_developer',168,'Royal Bank of Canada','Toronto, ON, Canada','23 days ago');
INSERT INTO jobs VALUES('Senior Software Development Engineer','senior_application_developer',169,'remitly','New Westminster, BC, Canada','');
INSERT INTO jobs VALUES('Senior Software Engineer, Data Platform','senior_application_developer',170,'Coinbase','Victoria, BC, Canada','9 hours ago');
INSERT INTO jobs VALUES('Staff Software Developer','staff_software_engineer',171,'WARNERMEDIA','Kanata, ON, Canada','');
INSERT INTO jobs VALUES('Staff Software Engineer - MTS 2','staff_software_engineer',172,'eBay','Toronto, ON, Canada','5 days ago');
INSERT INTO jobs VALUES('Senior Staff Software Engineer','staff_software_engineer',173,'Posting Date:07/ 08/2024','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Staff Frontend Software Engineer','staff_software_engineer',174,'Warner Music Group','Toronto, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Staff Software Engineer - Fullstack - Websites Team','staff_software_engineer',175,'Toast','Canada','');
INSERT INTO jobs VALUES('Staff Software Engineer - Incident Management','staff_software_engineer',176,'PagerDuty','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Staff Software Engineer, Infotainment Platform','staff_software_engineer',177,'Rivian','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES('Senior Staff / Principal Software Developer','staff_software_engineer',178,'Intuit','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Staff Software Engineer','staff_software_engineer',179,'Affinity.co','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Staff Software Engineer, Platform Engineering','staff_software_engineer',180,'Lime','Canada','8 days ago');
INSERT INTO jobs VALUES('Cloud Solution Engineer','cloud_engineer',181,'Royal Bank of Canada','Toronto, ON, Canada','6 days ago');
INSERT INTO jobs VALUES('AWS Cloud Engineer','cloud_engineer',182,'Thoughtworks','Toronto, ON, Canada','17 days ago');
INSERT INTO jobs VALUES('Azure Cloud Engineer','cloud_engineer',183,'EY','Toronto, ON, Canada','24 days ago');
INSERT INTO jobs VALUES('OpenShift Cloud Engineer (6 Months Contract)','cloud_engineer',184,'BDO Canada','Oakville, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('GCP Cloud engineer','cloud_engineer',185,'ARROWMINDS INC','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Cloud Developer','cloud_engineer',186,'Royal Bank of Canada','Toronto, ON, Canada','4 days ago');
INSERT INTO jobs VALUES('Network Cloud Engineer','cloud_engineer',187,'Cognizant','Brampton, ON, Canada','28 days ago');
INSERT INTO jobs VALUES('Cloud Solution Engineer','cloud_engineer',188,'Royal Bank of Canada','Calgary, AB, Canada','2 days ago');
INSERT INTO jobs VALUES('Cloud Engineer I','cloud_engineer',189,'Paymentus (Canada) Corporation','Richmond Hill, ON, Canada','');
INSERT INTO jobs VALUES('Cloud Systems Engineer','cloud_engineer',190,'PartnerRe','Toronto, ON, Canada','16 days ago');
INSERT INTO jobs VALUES('Senior Application Security Engineer','application_security_engineer',191,'Ouster','Ottawa, ON, Canada','');
INSERT INTO jobs VALUES('Application Security Engineer, ETSE','application_security_engineer',192,'Amazon','Vancouver, BC, Canada','22 days ago');
INSERT INTO jobs VALUES('Application Security Engineer','application_security_engineer',193,'Agoda','Vancouver, BC, Canada','20 days ago');
INSERT INTO jobs VALUES('Application Security Engineer','application_security_engineer',194,'Kraken Crypto Exchange','New Canada, NS, Canada','');
INSERT INTO jobs VALUES('Sr. Lead Application Security Engineer\u202f - Generative AI (Remote)','application_security_engineer',195,'S&P Global','Victoria, BC, Canada','7 days ago');
INSERT INTO jobs VALUES('Senior Application Security Engineer','application_security_engineer',196,'Score Media and Gaming Inc.','Canada','26 days ago');
INSERT INTO jobs VALUES('Sr. Application Security Specialist-Java (GCS)','application_security_engineer',197,'Royal Bank of Canada','Vancouver, BC, Canada','3 days ago');
INSERT INTO jobs VALUES('Principal Security Engineer - Application Security','application_security_engineer',198,'Gusto','Toronto, ON, Canada','20 days ago');
INSERT INTO jobs VALUES('Senior Application Security Engineer, ETSE','application_security_engineer',199,'Amazon','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES('Field Application Engineer','application_security_engineer',200,'McAfee','Waterloo, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Web Developer','senior_web_developer',201,'Autodesk','Montreal, Quebec, Canada','20 days ago');
INSERT INTO jobs VALUES('Web Software Developer - Front End (Senior)','senior_web_developer',202,'dakis','Montreal, Quebec, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Full Stack Web Developer','senior_web_developer',203,'Epic Games','British Columbia, Canada','17 days ago');
INSERT INTO jobs VALUES('Senior Website Software Development Engineer','senior_web_developer',204,'Advanced Micro Devices, Inc','Vancouver, BC, Canada','11 days ago');
INSERT INTO jobs VALUES('[Wattpad] Senior Web Engineer','senior_web_developer',205,'WEBTOON Entertainment Inc. (Wattpad & WEBTOON Family of Brands)','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Senior Full Stack Web Developer (Job Req #2024-285)','senior_web_developer',206,'Ross Video','Ottawa, ON, Canada','16 days ago');
INSERT INTO jobs VALUES('Senior Full Stack Web Developer','senior_web_developer',207,'TM8','Vancouver, BC, Canada','7 days ago');
INSERT INTO jobs VALUES('Senior Web Developer','senior_web_developer',208,'Voices','Waterloo, ON, Canada','9 days ago');
INSERT INTO jobs VALUES('Senior Web Designer','senior_web_developer',209,'Musora Media','Abbotsford, BC, Canada','9 days ago');
INSERT INTO jobs VALUES('Sr. Web Developer - AEC Integration','senior_web_developer',210,'Esri','Ottawa, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior Full-Stack PHP Developer, Services','php_developer',211,'Equisoft','Montreal, Quebec, Canada','');
INSERT INTO jobs VALUES('PHP Web Developer','php_developer',212,'WHC Online Solutions Inc.','Montreal, Quebec, Canada','');
INSERT INTO jobs VALUES('PHP Developers Canada','php_developer',213,'Kovasys','Canada','');
INSERT INTO jobs VALUES('Full-stack PHP developer','php_developer',214,'Graphically Speaking','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES('Senior PHP Developer','php_developer',215,'Software International','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Senior PHP Application Developer – CONTRACT','php_developer',216,'Ward Technology Talent','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('PHP Web Developer – Toronto,ON','php_developer',217,'Kovasys','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('PHP Developer','php_developer',218,'CB Canada','Markham, ON, Canada','');
INSERT INTO jobs VALUES('PHP Developer','php_developer',219,'Priyasoft Inc.','Brampton, ON, Canada','29 days ago');
INSERT INTO jobs VALUES('Canada: Intermediate PHP Developer (CANAD004002)','php_developer',220,'ScanSource Canada Inc.','Alberta, Canada','');
INSERT INTO jobs VALUES('AWS Security Engineer','security_engineer',221,'ProHire solutions','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Information Security Engineer','security_engineer',222,'CloudVital','Mississauga, ON, Canada','4 days ago');
INSERT INTO jobs VALUES('Cloud Security Engineer, Deloitte Global Technology','security_engineer',223,'Deloitte','Toronto, ON, Canada','19 days ago');
INSERT INTO jobs VALUES('Senior Security Detection Engineer (GCS)','security_engineer',224,'Royal Bank of Canada','Vancouver, BC, Canada','14 days ago');
INSERT INTO jobs VALUES('Intermediate Security Engineer, Corporate Security','security_engineer',225,'GitLab','Canada','18 days ago');
INSERT INTO jobs VALUES('Senior Security Engineer','security_engineer',226,'Dremio','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Lead Security Engineer, Identity and Access Management','security_engineer',227,'CPP Investments','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('Intermediate Security Engineer, Corporate Security','security_engineer',228,'GitLab','United States','19 days ago');
INSERT INTO jobs VALUES('Sr. Ruby on Rails Engineer (Security)','security_engineer',229,'Aha!','Halifax, NS, Canada','20 hours ago');
INSERT INTO jobs VALUES('Security Engineer - Encryption Engineer','security_engineer',230,'TD Bank','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('AWS DevOps Engineer','devops_engineer',231,'Group Nine LLC','Toronto, ON, Canada','3 days ago');
INSERT INTO jobs VALUES('Senior DevOps Engineer - Canada','devops_engineer',232,'SysAid Technologies','Toronto, ON, Canada','4 days ago');
INSERT INTO jobs VALUES('DevOps Engineer','devops_engineer',233,'Zurich Insurance Company Ltd.','Toronto, ON, Canada','19 days ago');
INSERT INTO jobs VALUES('Azure DevOps Engineer - Tech Lead','devops_engineer',234,'Lumenalta','Canada','2 hours ago');
INSERT INTO jobs VALUES('DevOps and Platforms Engineer','devops_engineer',235,'Royal Bank of Canada','Toronto, ON, Canada','21 days ago');
INSERT INTO jobs VALUES('DevOps Developer','devops_engineer',236,'Newfound Recruiting','Ottawa, ON, Canada','2 days ago');
INSERT INTO jobs VALUES('Senior DevOps Engineer (Senior Engineer)','devops_engineer',237,'NielsenIQ','Toronto, ON, Canada','10 days ago');
INSERT INTO jobs VALUES('Senior DevOps Engineer','devops_engineer',238,'Coconut Software','Saskatoon, SK, Canada','');
INSERT INTO jobs VALUES('DevOps Engineer','devops_engineer',239,'Randstad Canada','Victoria, BC, Canada','5 days ago');
INSERT INTO jobs VALUES('DevOps Engineer','devops_engineer',240,'Quarterhill','Saskatoon, SK, Canada','20 days ago');
INSERT INTO jobs VALUES('Business Intelligence Analyst/Developer','business_intelligence_developer',241,'Acunor','Toronto, ON, Canada','19 days ago');
INSERT INTO jobs VALUES('Business Intelligence Developer (RFT 1.0 FTE)','business_intelligence_developer',242,'The Royal','Ottawa, ON, Canada','');
INSERT INTO jobs VALUES('Business Intelligence & Reporting Developer','business_intelligence_developer',243,'Husky Technologies','Bolton, ON, Canada','9 days ago');
INSERT INTO jobs VALUES('Business Intelligence Developer (12-Month contract)','business_intelligence_developer',244,'Citco','Toronto, ON, Canada','1 month ago');
INSERT INTO jobs VALUES('BI Developer or Business Intelligence Developer','business_intelligence_developer',245,'TalentBurst Inc','Vancouver, BC, Canada','');
INSERT INTO jobs VALUES('Senior Business Intelligence Developer','business_intelligence_developer',246,'FGF Brands','Canada','19 days ago');
INSERT INTO jobs VALUES('Business Intelligence Developer','business_intelligence_developer',247,'Cineplex','Hunter River, PE, Canada','15 days ago');
INSERT INTO jobs VALUES('Senior Business Intelligence Consultant/Developer','business_intelligence_developer',248,'Alphabyte','Toronto, ON, Canada','9 days ago');
INSERT INTO jobs VALUES('Senior BI Developer, Lead Looker Developer','business_intelligence_developer',249,'Bitstrapped Inc','Toronto, ON, Canada','');
INSERT INTO jobs VALUES('BI & Data Visualization Developer','business_intelligence_developer',250,'McAfee, LLC','Canada','5 days ago');
